vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    salon_images:
      uri_prefix: /images/salon
      upload_destination: "%kernel.project_dir%/public/images/salon"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
